### ISSUE TITLE
Not able to Run the Project: Project Dependency - Node Sass Deprecated

### ISSUE THREAD

**Issue by Rahul4578** [Ayush-Kanduri/Placement-Cell-Application#3]
Please give explanation In detail  in youtube. I need it so please send me. Please contact me on 8874171910

**Comment by harika-2425** [comment]
Even I am not able to run thr code. 
Please help

**Comment by riddhinayi** [comment]
plz show the project ppt ?

**Comment by Ayush-Kanduri** [comment]
Apologies for the delayed response. I was dealing with some issues and was unable to be active.

The issue you're encountering is likely related to the node-sass package. Since npm packages are frequently updated or deprecated, there's no guarantee that they will function the same way as they did previously.
This is beyond my scope to resolve directly. You'll need to configure Node Sass and the other dependencies yourself, as this project is built on an outdated and deprecated version of Node Sass.

If you still want to go with Node Sass anyway, then
**Try this FIX:** 
1. Run this in terminal 
```
python -m ensurepip --upgrade
python -m pip install --upgrade pip setuptools
```

2. Run this in powershell as Admin
```
npm install --global windows-build-tools
```

3. Run this in terminal 
```
npm cache clean --force
npm install node-sass
```

4. Refer Project Readme for other issues.

If even this doesn't work, go for "sass" & try to match the node versions - 
```
npm uninstall node-sass
npm install sass
npm i
```
